from datetime import datetime, timezone
from typing import Dict, List, Any
from uuid import uuid4


class HunterService:
    """
    Hunter detects potential duplicate loan applications
    across participating bank tenants.

    Hunter does NOT declare a customer guilty of fraud.
    It generates a potential duplicate flag and routes
    the case for bank review.
    """

    def __init__(self):

        # MVP in-memory registry.
        # Can later be replaced by PostgreSQL/MongoDB.
        self.applications: List[Dict[str, Any]] = []

        # Hunter alerts
        self.alerts: List[Dict[str, Any]] = []

        # Audit events generated by Hunter
        self.audit_events: List[Dict[str, Any]] = []

    # =========================================================
    # CHECK APPLICATION
    # =========================================================

    def check_application(
        self,
        tenant_id: str,
        applicant_id: str,
        loan_type: str,
        loan_amount: float,
        application_id: str | None = None,
    ) -> Dict[str, Any]:

        if application_id is None:
            application_id = str(uuid4())

        # -----------------------------------------------------
        # Search for an ACTIVE application belonging to the
        # same applicant and same loan type at another bank.
        # -----------------------------------------------------

        duplicate = None

        for application in self.applications:

            if (
                application["applicant_id"] == applicant_id
                and application["loan_type"].lower()
                == loan_type.lower()
                and application["status"] == "ACTIVE"
                and application["tenant_id"] != tenant_id
            ):
                duplicate = application
                break

        # =====================================================
        # DUPLICATE FOUND
        # =====================================================

        if duplicate:

            new_application = {
                "application_id": application_id,
                "tenant_id": tenant_id,
                "applicant_id": applicant_id,
                "loan_type": loan_type,
                "loan_amount": loan_amount,
                "status": "FLAGGED",
                "created_at": self._timestamp(),
            }

            self.applications.append(new_application)

            # Create privacy-safe alerts
            alert = self._create_alert(
                applicant_id=applicant_id,
                current_application=new_application,
                existing_application=duplicate,
            )

            # Create audit event
            self._create_audit_event(
                applicant_id=applicant_id,
                tenant_id=tenant_id,
                application_id=application_id,
                duplicate_tenant_id=duplicate["tenant_id"],
                loan_type=loan_type,
            )

            return {
                "flagged": True,

                "flag_type":
                    "DUPLICATE_LOAN_APPLICATION",

                "severity": "HIGH",

                "message": (
                    "Potential duplicate loan application "
                    "detected across participating institutions."
                ),

                # Only return the current bank's application
                # rather than exposing another bank's record.
                "application": new_application,

                "alert": alert,

                "action": "BANK_REVIEW",
            }

        # =====================================================
        # NO DUPLICATE
        # =====================================================

        new_application = {
            "application_id": application_id,
            "tenant_id": tenant_id,
            "applicant_id": applicant_id,
            "loan_type": loan_type,
            "loan_amount": loan_amount,
            "status": "ACTIVE",
            "created_at": self._timestamp(),
        }

        self.applications.append(new_application)

        # Audit the normal Hunter check as well
        self._create_audit_event(
            applicant_id=applicant_id,
            tenant_id=tenant_id,
            application_id=application_id,
            duplicate_tenant_id=None,
            loan_type=loan_type,
            flagged=False,
        )

        return {
            "flagged": False,

            "flag_type": None,

            "severity": "LOW",

            "message":
                "No duplicate active loan application detected.",

            "application": new_application,

            "alert": None,

            "action": "CONTINUE",
        }

    # =========================================================
    # CREATE PRIVACY-SAFE ALERTS
    # =========================================================

    def _create_alert(
        self,
        applicant_id: str,
        current_application: Dict[str, Any],
        existing_application: Dict[str, Any],
    ) -> Dict[str, Any]:

        alert_id = str(uuid4())

        current_tenant = current_application[
            "tenant_id"
        ]

        existing_tenant = existing_application[
            "tenant_id"
        ]

        # -----------------------------------------------------
        # IMPORTANT:
        # Do NOT expose the complete application belonging
        # to another tenant.
        # -----------------------------------------------------

        alert = {
            "alert_id": alert_id,

            "alert_type":
                "DUPLICATE_LOAN_APPLICATION",

            "severity": "HIGH",

            "applicant_id": applicant_id,

            "loan_type":
                current_application["loan_type"],

            "status": "OPEN",

            "created_at": self._timestamp(),

            "message": (
                "Potential duplicate loan application "
                "detected. Bank review required."
            ),

            # Current bank receives its own alert
            "recipient_tenant_id": current_tenant,

            # Existing bank receives a separate alert.
            # We do not expose its application data.
            "related_institution_detected": True,

            "action": "BANK_REVIEW",
        }

        self.alerts.append(alert)

        # Create a second privacy-safe alert for
        # the institution holding the existing application.

        existing_bank_alert = {
            "alert_id": str(uuid4()),

            "alert_type":
                "DUPLICATE_LOAN_APPLICATION",

            "severity": "HIGH",

            "applicant_id": applicant_id,

            "loan_type":
                existing_application["loan_type"],

            "status": "OPEN",

            "created_at": self._timestamp(),

            "message": (
                "A potential duplicate loan application "
                "has been detected for this applicant."
            ),

            "recipient_tenant_id": existing_tenant,

            "related_institution_detected": True,

            "action": "BANK_REVIEW",
        }

        self.alerts.append(existing_bank_alert)

        return {
            "alert_id": alert_id,

            "recipient_tenant_id":
                current_tenant,

            "severity": "HIGH",

            "status": "OPEN",

            "action": "BANK_REVIEW",

            "message": (
                "Potential duplicate loan application "
                "detected."
            ),
        }

    # =========================================================
    # AUDIT EVENT
    # =========================================================

    def _create_audit_event(
        self,
        applicant_id: str,
        tenant_id: str,
        application_id: str,
        duplicate_tenant_id: str | None,
        loan_type: str,
        flagged: bool = True,
    ):

        event = {
            "event_id": str(uuid4()),

            "event_type":
                (
                    "HUNTER_DUPLICATE_DETECTED"
                    if flagged
                    else
                    "HUNTER_CHECK_COMPLETED"
                ),

            "tenant_id": tenant_id,

            "application_id":
                application_id,

            "applicant_id":
                applicant_id,

            "loan_type":
                loan_type,

            "duplicate_detected":
                flagged,

            # We record that another institution exists,
            # without exposing its application details.
            "cross_tenant_match":
                duplicate_tenant_id is not None,

            "timestamp":
                self._timestamp(),
        }

        self.audit_events.append(event)

    # =========================================================
    # BANK ALERTS
    # =========================================================

    def get_bank_alerts(
        self,
        tenant_id: str
    ):

        return [
            alert
            for alert in self.alerts
            if alert["recipient_tenant_id"]
            == tenant_id
        ]

    # =========================================================
    # APPLICATIONS
    # =========================================================

    def get_applications(
        self,
        tenant_id: str | None = None
    ):

        if tenant_id is None:
            return self.applications

        return [
            application
            for application in self.applications
            if application["tenant_id"] == tenant_id
        ]

    # =========================================================
    # ALL ALERTS
    # =========================================================

    def get_alerts(
        self,
        tenant_id: str | None = None
    ):

        if tenant_id is None:
            return self.alerts

        return self.get_bank_alerts(
            tenant_id
        )

    # =========================================================
    # AUDIT EVENTS
    # =========================================================

    def get_audit_events(
        self,
        tenant_id: str | None = None
    ):

        if tenant_id is None:
            return self.audit_events

        return [
            event
            for event in self.audit_events
            if event["tenant_id"] == tenant_id
        ]

    # =========================================================
    # TIMESTAMP
    # =========================================================

    @staticmethod
    def _timestamp():

        return datetime.now(
            timezone.utc
        ).isoformat()


hunter_service = HunterService()